services:
  #servicio de postgre
  db:
    image: postgres:15
    container_name: blockrott-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiempouso
      POSTGRES_DB: ServidorTiempoUso
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  #servcio springboot
  app:
    build: .
    container_name: blockrott-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ServidorTiempoUso
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiempouso
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    restart: always

volumes:
  postgres_data: